### ISSUE TITLE
Investigate why mean points are all-zero on CMIP6 Maximum 1-day Precipitation charts

### ISSUE THREAD

**Issue by cstephen** [ua-snap/ardac-explorer#135]
The CMIP6 Maximum 1-day Precipitation looks like this:

![image](https://github.com/user-attachments/assets/47f54a0b-b8ec-4e93-8c39-9d0f3437bdc2)

This is the only one of the four CMIP6 indicators with this chart problem.

I'm sure I would have noticed this issue while developing these charts, so I think this problem may have been an inadvertent side effect from PR #111. In any case, I think we can fix this easily enough by tweaking the value thresholds of the `precisionMean` function that was added in PR #111.

**Comment by brucecrevensten** [comment]
I can't recreate this issue from `main` anymore.  @cstephen please re-test and close if you can't see it either.

**Comment by cstephen** [comment]
Looks like this fixed itself automagically after we updated the `cmip6_indicators` coverage because the new coverage + API outputs serve "CMIP6 Maximum 1-day Precipitation" data in millimeters, not meters, so the super tiny values & rounding problems have gone away.
