### ISSUE TITLE
Lock y-axis for xray items which allow model, scenario selections

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ardac-explorer#154]
Need to perhaps flesh this out a bit more or iterate, but as a first step, consider clamping the y-axis for the CMIP6 xray items against the max/min values in the data.  This makes it easier to make visual comparisons between models and scenarios.

Months pose a bit of a problem/special case.  Do we clamp this against the entire years' value?  Or within the specific month selected?  The latter might make more sense.

**Comment by cstephen** [comment]
CMIP6 & CMIP6 indicators y-axis clamping was implemented in #169, and we decided to hold off on putting extra work into old ARDAC items, so I'm going to close this issue.
